gem 'activerecord'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'rake'
gem 'require_all'
gem 'rubocop', '~>0.81.0'
gem 'securerandom', '~> 0.1.0'
gem 'sinatra'
gem 'telegram-bot-ruby'
source 'https://rubygems.org'
